name: Build and Publish

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --release --verbose

    - name: Install cargo-deb
      run: cargo install cargo-deb

    - name: Build deb
      run: cargo deb

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Get current version
      id: get_version
      run: echo "version=$(cargo pkgid | sed 's/.*#//')" >> $GITHUB_ENV

    - name: Get published version
      id: get_published_version
      run: |
        published_version=$(cargo search $(cargo pkgid | sed 's/.*#//' | cut -d: -f1) --limit 1 | grep -oP '\(\K[^)]+' | head -1)
        echo "published_version=$published_version" >> $GITHUB_ENV

    - name: Compare versions
      id: compare_versions
      run: |
        if [ "$(echo -e "${published_version}\n${version}" | sort -V | head -n1)" != "$version" ]; then
          echo "newer_version=true" >> $GITHUB_ENV
        else
          echo "newer_version=false" >> $GITHUB_ENV

    - name: Publish to crates.io
      if: ${{ env.newer_version == 'true' }}
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish --no-verify

